
import { MarketplaceListing } from "@/types/firestore";

function ts(minutesAgo: number) {
    const now = Date.now();
    const seconds = Math.floor((now - minutesAgo * 60 * 1000) / 1000);
    return { seconds, nanoseconds: 0 } as any;
}

export const MOCK_LISTINGS: MarketplaceListing[] = [
    {
        id: 'mock_1',
        sellerId: 'bot_gamma',
        sellerName: 'Gamma',
        type: 'pet_lend',
        title: 'Max Stat Storm Pet (Quad Dmg)',
        description: 'Perfect for leveling. 2.0 Stats.',
        batchSize: 1,
        availableBatches: 5,
        allowPartial: false,
        currency: 'empowers',
        pricePerBatch: 50,
        status: 'active',
        createdAt: ts(5),
    },
    {
        id: 'mock_2',
        sellerId: 'bot_ambrose',
        sellerName: 'Headmaster Ambrose',
        type: 'tc_pack',
        title: '999x Empowers (Bulk)',
        description: 'Restocking the bazaar.',
        batchSize: 999,
        availableBatches: 10,
        allowPartial: true,
        currency: 'empowers',
        pricePerBatch: 1000,
        status: 'active',
        createdAt: ts(15),
    },
    {
        id: 'mock_3',
        sellerId: 'bot_cyrus',
        sellerName: 'Cyrus Drake',
        type: 'carry_service',
        title: 'Darkmoor Full Run (Gold Key)',
        description: 'Do not waste my time.',
        batchSize: 1,
        availableBatches: 3,
        allowPartial: false,
        currency: 'empowers',
        pricePerBatch: 200,
        status: 'active',
        createdAt: ts(45),
    },
    {
        id: 'mock_4',
        sellerId: 'bot_dworgyn',
        sellerName: 'Dworgyn',
        type: 'pet_lend',
        title: 'Triple Double Death Pet',
        description: 'Scary good stats!',
        batchSize: 1,
        availableBatches: 3,
        allowPartial: false,
        currency: 'empowers',
        pricePerBatch: 45,
        status: 'active',
        createdAt: ts(120),
    },
    {
        id: 'mock_5',
        sellerId: 'bot_belladonna',
        sellerName: 'Belladonna Crisp',
        type: 'pet_lend',
        title: 'Wysteria Ward Pet',
        description: 'For defensive wizards.',
        batchSize: 1,
        availableBatches: 2,
        allowPartial: false,
        currency: 'empowers',
        pricePerBatch: 60,
        status: 'active',
        createdAt: ts(180),
    },
    {
        id: 'mock_6',
        sellerId: 'bot_gamma',
        sellerName: 'Gamma',
        type: 'tc_pack',
        title: '50x Elucidate',
        description: 'Rare cards from the archives.',
        batchSize: 50,
        availableBatches: 1,
        allowPartial: true,
        currency: 'empowers',
        pricePerBatch: 5000,
        status: 'active',
        createdAt: ts(240),
    },
    {
        id: 'mock_7',
        sellerId: 'bot_alhazred',
        sellerName: 'Alhazred',
        type: 'carry_service',
        title: 'Krokotopia Badge Help',
        description: 'Balance in all things.',
        batchSize: 1,
        availableBatches: 5,
        allowPartial: false,
        currency: 'empowers',
        pricePerBatch: 20,
        status: 'active',
        createdAt: ts(300),
    }
];
